# Generated by Django 3.0.2 on 2021-05-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210528_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'customer'), ('seller', 'seller'), ('staff', 'staff')], max_length=30),
        ),
    ]
